apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flu-es
  namespace: kube-system
  labels:
    k8s-app: flu-log
spec:
  selector:
    matchLabels:
      name: flu-es
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: flu-es
    spec:
      containers:
      - name: flu-es
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
        - name: testenv
          value: value
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
