apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcron
spec:
  schedule: "*/1 * * * *"# 1/1min
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: testcronctn
            image: busybox
            args: ["sh", "-c", "date",]
